title: FloydHub Blog
description: Learn about Deep Learning
author: FloydHub Team
email: blog@floydhub.com
baseurl: ""
url: "https://floydhub.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Permalink structure to match Ghost URLs (no date in URL)
permalink: /:title/

plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - floydhub-blog.ghost.2025-09-24-21-16-37.json